### ISSUE TITLE
Software Boutique lacks translations.

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-welcome-legacy#12]
Originally reported by: **Luke Horwell (Bitbucket: [lah7](https://bitbucket.org/lah7), GitHub: [lah7](https://github.com/lah7))**

----------------------------------------

A bit of an awkward situation with the current implementation of `applications.json` containing the strings. On the upside, they can be easily interfaced using JSON.

A "middle ground" would need to be written to interface with PO/POT files so they are:

* Translatable on Transflex.
* Can be read and displayed for the Boutique.

----------------------------------------
- Bitbucket: https://bitbucket.org/ubuntu-mate/ubuntu-mate-welcome/issue/12

**Comment by flexiondotorg** [comment]
*Original comment by* **Rob Loach (Bitbucket: [RobLoach](https://bitbucket.org/RobLoach), GitHub: [RobLoach](https://github.com/RobLoach))**:

----------------------------------------

When running, I'm getting....


```
#!txt
[i18n] Locale Not Available: en_US (using en_US instead)
[i18n] Locale Not Available: en (using en_US instead)
Traceback (most recent call last):
  File "./ubuntu-mate-welcome", line 663, in __init__
    t = gettext.translation('ubuntu-mate-welcome', localedir=i18n_path, languages=[self.locale])
  File "/usr/lib/python3.5/gettext.py", line 432, in translation
    raise OSError(ENOENT, 'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'ubuntu-mate-welcome'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./ubuntu-mate-welcome", line 2690, in <module>
    trans = Translations(data_path)
  File "./ubuntu-mate-welcome", line 668, in __init__
    t = gettext.translation('ubuntu-mate-welcome', localedir='/usr/share/locale/')
  File "/usr/lib/python3.5/gettext.py", line 432, in translation
    raise OSError(ENOENT, 'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'ubuntu-mate-welcome'

```

**Comment by flexiondotorg** [comment]
*Original comment by* **Luke Horwell (Bitbucket: [lah7](https://bitbucket.org/lah7), GitHub: [lah7](https://github.com/lah7))**:

----------------------------------------

That bug has been fixed in recent commits. This also isn't related to the lack of translations for the Boutique.
