### ISSUE TITLE
Problems in Linux Mint 18

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-welcome-legacy#24]
Originally reported by: **Polihron Alexandru (Bitbucket: [APoliTech](https://bitbucket.org/APoliTech), GitHub: [APoliTech](https://github.com/APoliTech))**

----------------------------------------

The app wont open. i did installed via software center and .deb file but i get this error 

polihron@LinuxLaptop ~ $ ubuntu-mate-welcome
[i18n] Locale Not Available: en_US (using en_US instead)
[i18n] Locale Not Available: en (using en_US instead)
Traceback (most recent call last):
  File "/usr/bin/ubuntu-mate-welcome", line 3173, in <module>
    systemstate = SystemState()
  File "/usr/bin/ubuntu-mate-welcome", line 1293, in __init__
    self.autostart = self.autostart_check()
  File "/usr/bin/ubuntu-mate-welcome", line 1391, in autostart_check
    os.makedirs(_dir)
NameError: name '_dir' is not defined

and

polihron@LinuxLaptop ~ $ ubuntu-mate-welcome --boutique
[Welcome] Starting in Software Boutique mode.
[i18n] Locale Not Available: en_US (using en_US instead)
[i18n] Locale Not Available: en (using en_US instead)
Traceback (most recent call last):
  File "/usr/bin/ubuntu-mate-welcome", line 3173, in <module>
    systemstate = SystemState()
  File "/usr/bin/ubuntu-mate-welcome", line 1293, in __init__
    self.autostart = self.autostart_check()
  File "/usr/bin/ubuntu-mate-welcome", line 1391, in autostart_check
    os.makedirs(_dir)
NameError: name '_dir' is not defined

----------------------------------------
- Bitbucket: https://bitbucket.org/ubuntu-mate/ubuntu-mate-welcome/issue/24

**Comment by flexiondotorg** [comment]
*Original comment by* **Luke Horwell (Bitbucket: [lah7](https://bitbucket.org/lah7), GitHub: [lah7](https://github.com/lah7))**:

----------------------------------------

Thanks for the report. There was a variable issue which I've fixed (and pending merging).

The locale issue is expected at the moment due to missing translations for pages, but it will still run.

**Comment by flexiondotorg** [comment]
*Original comment by* **Polihron Alexandru (Bitbucket: [APoliTech](https://bitbucket.org/APoliTech), GitHub: [APoliTech](https://github.com/APoliTech))**:

----------------------------------------

Yea i know about the translation! Great job with this app @lah7

**Comment by flexiondotorg** [comment]
*Original comment by* **Martin Wimpress (Bitbucket: [flexiondotorg](https://bitbucket.org/flexiondotorg), GitHub: [flexiondotorg](https://github.com/flexiondotorg))**:

----------------------------------------

Fix autostart directory variable. Closes #24.
